### ISSUE TITLE
Parameter 2 to stanford_courses_feeds_presave() expected to be a reference, value given module.inc:895 

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/stanford_courses#37]
Bug introduced here:
https://github.com/SU-SWS/stanford_courses/commit/627b1ac7ef752e94097a342267a88376c34cfa59

**Comment by sherakama** [comment]
Sloppy developer. Gack.

**Comment by jbickar** [comment]
Give that developer back his cookie.
