### ISSUE TITLE
Version 3.9 does not pull section information into drupal install

### ISSUE THREAD

**Issue by irinaz** [SU-SWS/stanford_courses#57]
Hi, 
I used newest release 3.9 and section information in not being saved in course content type.  I have tested importer and I can see that data is being parsed correctly after feed import, but when I look at imported courses section data is missing.

**Comment by sherakama** [comment]
This might have to do with this commit: https://github.com/SU-SWS/stanford_courses/commit/991b665985366f6a38f5fa1f867037c27d8f3969

If you have access to drush try `drush vset stanford_courses_limit_field_collections 100`

**Comment by irinaz** [comment]
@sherakama 
thanks, it helped to solve our issue

**Comment by sherakama** [comment]
I think we do have an issue here. It should pull by default and not after the vset.

**Comment by irinaz** [comment]
@sherakama  We might have had issues with our local install - I am testing now on another brand new instance and it seems to be working now.  I think that maybe we had some modules that were not properly updated, or some weird modifications.   Today I did completely new install, and 3.9 seems to work as well as 3.6.  I think that we can close this issue, I will report it again if I can find the problem. 

thanks!!!

**Comment by sherakama** [comment]
Great.

Thanks for the follow up. Much appreciated.

**Comment by irinaz** [comment]
Today I ran full update on my local instance on all modules, including feeds, features, field collection, etc.
Now I cannot not pull section information from explorecourses via course importer.  I will continue testing and hope to report the problem if I find it.

**Comment by sherakama** [comment]
Hello @irinaz,

I just ran an import with the latest 7.x-3.x dev branch and I was successfully able to import sections.

Could you provide me with the feed url for the feed you are trying to import?

Thanks

**Comment by irinaz** [comment]
Hi Shea,
Thank you SO MUCH for looking into this.   I suspect that problem is on 
our end.  Here is information

Course page   http://student-reports.law.stanford.edu/node/3/edit
Course importer page 
http://student-reports.law.stanford.edu/node/2/edit?destination=admin/content

I added you as admin to this site.

Thanks a lot, Irina

**Comment by sherakama** [comment]
Hello Irina,

I was able to successfully import using the same xml feed as you have in student-reports. It looks like something on your end. 

Try updating your versions of entity, feeds, field_collection, and stanford_courses. You may have better luck.

**Comment by irinaz** [comment]
Hi Shea ,
We have tested updates to modules one by one the following upgrade breaks section import.
 
Feeds (feeds) 7.x-2.0-alpha9  ---> 7.x-2.0-beta2 - no section information is imported.

For our project will will downgrade to Feeds (feeds) 7.x-2.0-alpha9, but I wanted to report to you results of our testing
